version: '3.8'

services:
  postgresql:
    image: postgres:15.2
    environment:
      POSTGRES_USER: ${DB_USER:?is it defined in .env?}
      POSTGRES_PASSWORD: ${DB_PASSWORD:?is it defined in .env?}
      POSTGRES_DB: ${DB_NAME:?is it defined in .env?}
